### PR TITLE
432 token values should be trimmed on input and when passing to figma

### LINKED ISSUE #432: Token values should be trimmed on input and when passing to Figma
**Describe the bug**
#hex color sometimes won't work

**To Reproduce**
1. open plugin
2. create new color token
3. enter hex code
4. update style -> style with no property(in token panel it shows the color)

**Expected behavior**
when inputting hex code in the token panel and updating the color style, style should not be "no property". The property needs to align the color input in the token panel.

**Screenshots or Screencasts**
Screen Shot 2022-02-03 at 10 10 39 AM

**Figma file (optional)**
Send us the link to a Figma file containing a reproducible example

**JSON (optional)**
If possible, attach the JSON that leads to this bug.

### PR DESCRIPTION
**Pull request by swordEdge**
Fixes #432

### CODE REVIEW

File: src/app/components/EditTokenForm.tsx [hunk 1]
```diff
@@ -184,6 +184,23 @@ function EditTokenForm({ resolvedTokens }: Props) {
     [internalEditToken],
   );
 
+  const trimValue = React.useCallback((value: SingleToken['value']) => {
```
Comment (LiamMartens) [inline src/app/components/EditTokenForm.tsx:187]: Might be worth moving this to it's own utility function. That way we can more easily write a full coverage test for this as well.

**Review by LiamMartens — CHANGES_REQUESTED** [review]

**Review by LiamMartens — APPROVED** [review]
